version: '2'
services:
  jhipsterdemo01sqlserver-app:
    image: jhipsterdemo01sqlserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipsterdemo01sqlserver-mssql:1433;database=jhipsterDemo01SqlServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterdemo01sqlserver-mssql:
    extends:
      file: mssql.yml
      service: jhipsterdemo01sqlserver-mssql
